apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helloworld
spec:
  params:
  - name: username
    type: string
  steps:
    - name: 
      image: ubuntu
      script: helloworld
        #!/bin/bash
        echo "Hello World $(params.username)!"